spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      # 모든 라우터에 적용되는 기본 필터 설정하기.
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway GlobalFilter
            preLogger: true
            postLogger: true
      # 게이트 웨이 라우터 정의하기
      routes:
        - id: user-service # 식별 id
          uri: lb://USERS-SERVICE # 연결되는 대상 서비스의 주소를 사용한다는 의미
          predicates:
            - Path=/users-service/** # 라우트 매칭 조건을 정의한다.
        - id: catalog-service
          uri: lb://CATALOG-SERVICE
          predicates:
            - Path=/catalog-service/**
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order-service/**
server:
  port: 8000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

